name: plasma-template-crash-test
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  # Jupyter dependencies
  - jupyterhub>=1.5,<2
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
  # Python environment
  - python>=3.8
  - pip
  - numpy
  - pandas
  - matplotlib
  - ipywidgets>=7.6,<8
  # R environment
  - r-irkernel
  - r-base>=4
  - r-tidyverse
  # Variable inspector for R
  - r-repr
  # Jupyter archive
  - jupyter-archive
  - pip:
    - bash_kernel
    # Variable inspector
    - lckr-jupyterlab-variableinspector

